# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(\.mypy_cache|dist/|\.pytest_cache|\.idea|\.git)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: local
    hooks:
        - id:  mypy
          name: mypy
          language: system
          entry: ./scripts/run_mypy.sh

        - id: pylint
          name: pylint
          entry: pylint -j 2 -d consider-using-f-string
          language: system
          types: [ python ]

        - id: pytest
          name: pytest
          language: system
          entry: pytest tests
          types:
            - python
