version: '3.5'

networks:
  gemini:
    name: gemini
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24

services:
  gemini-oracle:
    image: scylladb/scylla-enterprise:2021.1.12
    container_name: gemini-oracle
    restart: always
    networks:
      gemini:

  gemini-test:
    image: scylladb/scylla-enterprise:2021.1.12
    container_name: gemini-test
    command: --smp 1 --memory 128M --api-address 0.0.0.0
    networks:
      gemini:
